-- Print Shop — PostgreSQL schema (manifest §requiredSchema contract).
--
-- This is the real database behind the full self-host stack: the shop reads it
-- (through Adminium's records API) and the auto-generated Adminium dashboard is
-- the back office. Applied automatically on first boot of the `works-db`
-- container via /docker-entrypoint-initdb.d/01-schema.sql, then seeded by
-- db/seed.sql. The seed mirrors src/data/demo.ts row for row — the same
-- fourteen live jobs, the same nine stock rows, the same pinned Wednesday — so
-- the shop floor and the dashboard run the same works.
--
-- THE NINE TABLES BELOW ARE THE MANIFEST'S, exactly: every table and every
-- column here appears in `requiredSchema` in manifest.json, and nothing else
-- does. That document is the contract three add-ons read (`design-studio`,
-- `shipping-dhl` and `import-canva` name `jobs` and `materials` in their
-- scopes), so a column added here and not there is a promise only half made.
--
-- WHAT IS DERIVED IS NOT STORED. The imposition (how many up, rotated or not,
-- how many sheets), what a material has committed to open jobs, whether a job
-- is overdue, its unit price, its customer-facing stage — all computed, in
-- src/lib/jobs.ts and src/lib/quote.ts in the app and in a query on the
-- dashboard side. The one exception is `jobs.total` and `quotes.total`, which
-- ARE stored, because a price is not a derivation of the rate card: it is what
-- the customer was told, and the rate card moves. Recomputing an old job's
-- total from today's rates would quietly re-invoice work that was already sold.
--
-- THE PROOF GATE IS NOT IN THIS FILE, and that is deliberate. `moveJob()` in
-- src/lib/jobs.ts refuses to take a job out of prepress until a proof is
-- approved, and it names what is missing when it refuses. Saying the same thing
-- here would take a CHECK that joins to `proofs`, which Postgres will not do
-- and a trigger would only pretend to — and a rule enforced in two places drifts
-- in one of them. The gate lives in the engine; the engine is tested.
--
-- Money is numeric(12, 2) — never a float; the engine works in whole cents and
-- divides once, at the edge. Millimetres are numeric because a trim size can be
-- half a millimetre. `promised_for` and a proof's `at` are `date`: a job is
-- promised FOR Thursday, not for an instant on it. A dispatch and a stock
-- movement are `timestamptz`, because those happened at a moment somebody could
-- point at.

DROP TABLE IF EXISTS stock_movements CASCADE;
DROP TABLE IF EXISTS dispatches CASCADE;
DROP TABLE IF EXISTS proofs CASCADE;
DROP TABLE IF EXISTS artwork CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS quotes CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- The counter ----------------------------------------------------------------

-- Invented small businesses in and around one market town. A works this size
-- knows its customers by name, which is why there is no account, no contact
-- hierarchy and no billing address here: one row is one firm.
CREATE TABLE customers (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  email      text NOT NULL,
  town       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX customers_email_idx ON customers (lower(email));

-- The catalogue --------------------------------------------------------------

-- What the works prints. `key` is what the app's option graph calls it
-- (`src/lib/catalogue.ts`) and what the eight locales translate; `name` is the
-- en-US label, so the dashboard has something readable in a column header.
--
-- The option graph itself — which materials make this product, which sizes it
-- comes in, which finishes it offers — is NOT here. It is a graph with a
-- compatibility matrix hanging off it, every edge of which carries the REASON a
-- combination is refused, and flattening that into join tables would leave the
-- reasons behind. It lives in `catalogue.ts` and the dashboard does not edit it.
CREATE TABLE products (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key           text NOT NULL UNIQUE,
  name          text NOT NULL,
  family        text NOT NULL CHECK (family IN
                  ('card', 'paper', 'mail', 'label', 'large', 'fabric')),
  -- The quantity the products grid's "from $X" figure is quoted at.
  from_quantity integer NOT NULL CHECK (from_quantity > 0),
  sides_choice  boolean NOT NULL
);

-- The shelf, and the rate card's one editable price.
--
-- `on_hand` and `reorder_at` count PRESS SHEETS for sheet stock and METRES for
-- roll media — one column, two units, exactly as `StockRow` in lib/jobs.ts
-- defines them. A 50m roll of banner PVC has no sheets to count.
--
-- `gsm` is null where grammage is not how the material is sold: self-adhesive
-- vinyl has a caliper, not a weight, and 0 g/m² would be a lie a chart would
-- happily plot.
CREATE TABLE materials (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        text NOT NULL UNIQUE,
  name       text NOT NULL,
  kind       text NOT NULL CHECK (kind IN ('sheet', 'roll')),
  gsm        integer CHECK (gsm > 0),
  -- Per SRA3 sheet for sheet stock, per square metre for roll media.
  sheet_cost numeric(12, 2) NOT NULL CHECK (sheet_cost >= 0),
  on_hand    integer NOT NULL CHECK (on_hand >= 0),
  reorder_at integer NOT NULL CHECK (reorder_at >= 0)
);

CREATE INDEX materials_kind_idx ON materials (kind);

-- What a customer priced and did not order.
--
-- `configuration` is the configurator's own object, stored whole: product,
-- material, size, sides, finish, quantity, packaging, proof, express and
-- delivery. Whole, because the point of a saved quote is that it can be loaded
-- BACK into the configurator months later, and a quote unpicked into fifteen
-- columns is a quote that has to be reassembled by hand every time the
-- configurator gains an option.
CREATE TABLE quotes (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref           text NOT NULL UNIQUE,
  customer_id   integer NOT NULL REFERENCES customers (id),
  -- A name the customer gave it, if any. Most are unnamed.
  label         text,
  configuration jsonb NOT NULL,
  total         numeric(12, 2) NOT NULL CHECK (total >= 0),
  saved_on      date NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX quotes_customer_idx ON quotes (customer_id);

-- The works ------------------------------------------------------------------

-- One job is one thing being printed, from the moment it is quoted to the
-- moment it leaves.
--
-- The trim size is stored in millimetres rather than as a preset key, because
-- half the work off the wide roll has no preset: a 900 × 2000mm banner is a
-- size somebody typed. The finish and the packaging ARE keys — closed
-- vocabularies from src/lib/rates.ts, spelled out in the CHECKs below so a
-- typo cannot reach the shop floor as a finish nobody offers.
--
-- `spoiled_sheets` is the one number the customer never sees: sheets the run
-- lost, added to what comes off the shelf, with the quoted price standing
-- still. That asymmetry is the whole reason it is a column rather than an
-- adjustment to `quantity`.
CREATE TABLE jobs (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref            text NOT NULL UNIQUE,
  customer_id    integer NOT NULL REFERENCES customers (id),
  product_id     integer NOT NULL REFERENCES products (id),
  material_id    integer NOT NULL REFERENCES materials (id),
  quantity       integer NOT NULL CHECK (quantity > 0),
  trim_width_mm  numeric(8, 1) NOT NULL CHECK (trim_width_mm > 0),
  trim_height_mm numeric(8, 1) NOT NULL CHECK (trim_height_mm > 0),
  sides          integer NOT NULL CHECK (sides IN (1, 2)),
  finish_key     text NOT NULL CHECK (finish_key IN
                   ('none', 'gloss-lam', 'matt-lam', 'soft-touch', 'spot-uv',
                    'round-corners', 'plain-edges', 'hemmed', 'pole-pockets',
                    'stretched', 'rolled')),
  packaging_key  text NOT NULL CHECK (packaging_key IN
                   ('bundled', 'shrink-wrapped', 'boxed')),
  -- The job machine, in the order it runs. `JOB_STAGES` in src/lib/jobs.ts is
  -- the same list, and src/manifest.test.ts fails the build if the manifest
  -- and the engine ever disagree about it.
  stage          text NOT NULL CHECK (stage IN
                   ('quoted', 'ordered', 'prepress', 'proofed', 'approved',
                    'printing', 'finishing', 'ready', 'dispatched', 'collected')),
  promised_for   date NOT NULL,
  express        boolean NOT NULL DEFAULT false,
  spoiled_sheets integer NOT NULL DEFAULT 0 CHECK (spoiled_sheets >= 0),
  -- What the customer was quoted, tax included. See the header.
  total          numeric(12, 2) NOT NULL CHECK (total >= 0),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX jobs_stage_idx ON jobs (stage);
CREATE INDEX jobs_customer_idx ON jobs (customer_id);
CREATE INDEX jobs_promised_idx ON jobs (promised_for);

-- A file a customer sent, and the numbers the checks measured on it.
--
-- The measurements are stored rather than re-measured because they are what the
-- customer was SHOWN and, in the case of a warning they ticked to accept, what
-- they agreed to. Re-deriving them from the file later — with a different
-- library, or a different version of the same one — could quietly disagree with
-- the verdict somebody signed off.
CREATE TABLE artwork (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id         integer NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
  filename       text NOT NULL,
  file           bytea NOT NULL,
  width_px       integer NOT NULL CHECK (width_px > 0),
  height_px      integer NOT NULL CHECK (height_px > 0),
  width_mm       numeric(8, 1) NOT NULL CHECK (width_mm > 0),
  height_mm      numeric(8, 1) NOT NULL CHECK (height_mm > 0),
  bleed_mm       numeric(5, 1) NOT NULL CHECK (bleed_mm >= 0),
  -- How close the nearest ink comes to the trim. Under the safe area this is a
  -- warning the customer accepts, not a refusal.
  nearest_ink_mm numeric(5, 1) NOT NULL CHECK (nearest_ink_mm >= 0),
  colour_space   text NOT NULL CHECK (colour_space IN ('CMYK', 'RGB')),
  fonts_embedded boolean NOT NULL,
  pages          integer NOT NULL CHECK (pages > 0),
  -- Which add-on produced it, when one did. Null for a plain upload.
  source         text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX artwork_job_idx ON artwork (job_id);

-- The proof conversation, in order: sent, a change asked for, sent again,
-- approved. A job's proofs are the evidence behind the gate in `moveJob()`,
-- which is why they are rows rather than a status column — "approved" is an
-- event with a date on it, and the round trips before it are the argument for
-- having a gate at all.
CREATE TABLE proofs (
  id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id integer NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
  kind   text NOT NULL CHECK (kind IN ('sent', 'change-asked', 'approved')),
  -- What the customer asked for, on a `change-asked`. Null on the others.
  note   text,
  at     date NOT NULL
);

CREATE INDEX proofs_job_idx ON proofs (job_id);

-- How the job left: over the counter, or with a carrier. One row per job — a
-- job leaves once — and a collection has no tracking number, because nobody
-- tracks a walk to the counter.
CREATE TABLE dispatches (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id   integer NOT NULL UNIQUE REFERENCES jobs (id) ON DELETE CASCADE,
  kind     text NOT NULL CHECK (kind IN ('collected', 'carrier')),
  tracking text,
  at       timestamptz NOT NULL,

  CONSTRAINT dispatches_tracking_ck CHECK (kind = 'carrier' OR tracking IS NULL)
);

-- The stock ------------------------------------------------------------------

-- What actually came off the shelf, and what arrived on it. Same two units as
-- `materials.on_hand`: press sheets for sheet stock, metres for roll media.
--
-- THIS LEDGER DOES NOT ADD UP TO `on_hand`, and is not meant to. `on_hand` is
-- what the last stock take counted; these are the movements since. A works that
-- derived its shelf from a movement history would be one miscounted delivery
-- away from ordering paper it already has.
--
-- A consumption belongs to a job and a delivery does not, which the CHECK says
-- outright rather than leaving to whoever writes the next insert.
CREATE TABLE stock_movements (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id integer NOT NULL REFERENCES materials (id),
  job_id      integer REFERENCES jobs (id) ON DELETE CASCADE,
  kind        text NOT NULL CHECK (kind IN ('consumed', 'spoilage', 'delivery')),
  sheets      integer NOT NULL CHECK (sheets > 0),
  at          timestamptz NOT NULL,

  CONSTRAINT stock_movements_job_ck CHECK ((kind = 'delivery') = (job_id IS NULL))
);

CREATE INDEX stock_movements_material_idx ON stock_movements (material_id, at DESC);
CREATE INDEX stock_movements_job_idx ON stock_movements (job_id);
